name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
   #Java 11
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
    # Selenoid
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
    #chmod
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #Run test
    - name: Run test
      run: ./gradlew clean test --info -Dselenide.remote=http://localhost:4444/wd/hub
