name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      #Java 11
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
      #Selenoid
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      #chmod
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      #Run test
      - name: Run test
        run: ./gradlew clean test --info -Dselenide.remote=http://localhost:4444/wd/hub
      #Allure скачиваем историю тестов
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #генерируем отчёт
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      #publish on GitHub Pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
